= Portfolio Architecture Healthcare Collection
Eric D. Schabell @eschabell
:homepage: https://gitlab.com/osspa/portfolio-architecture-examples
:imagesdir: images
:icons: font
:source-highlighter: prettify


This is a collection of various architectures in the healthcare domain. Our world transformed overnight, and
healthcare had to respond immediately. Now more than ever, it's critical to have access to data and unlimited scale,
and to design and modify decisioning, processes, and workflows for specific situations—without being vendor-dependent.

[cols="3,7"]
|===
|Title | Description   

|link:idaas.adoc[Intelligent data as a service (iDaaS)]
|Intelligent DaaS (Data as a Service) is about building and delivery of systems and platforms in a secure and scalable
manner while driving data needs for moving towards consumerisation in healthcare.

|link:edge-medical-diagnosis.adoc[Edge medical diagnosis]
|Accelerating medical diagnosis using condition detection in medical imagery with AI/ML at medical facilities.
|===

