= Red Hat Portfolio Architecture Examples
Eric Schabell @eschabell, Marty Wesley @mwesley_redhat, William Henry @ipbabble, Will Nix @tronik, Ishu Verma  @ishuverma, Marcos Entenza @makentenza
:homepage: https://gitlab.com/redhatdemocentral/portfolio-architecture-examples
:imagesdir: images
:icons: font
:source-highlighter: prettify

== Overview
This repository provides examples of customer implementations using Red Hat product portfolio. These architectural blueprints can be
used as is or adapted to meet the customer requirements. The architectural diagrams are created using the open source tool draw.io.

The examples include high level *Logical* diagrams, more in-depth view of how the various components and services work together in
*Schematic* diagrams and core functions associated with a particular service or component in *Detailed* diagrams. 

Select any Portfolio Architecture link in the table below to explore their diagrams.

TIP: Learn how to use the draw.io tool to create portfolio architecture diagrams with https://gitlab.com/redhatdemocentral/portfolio-architecture-workshops[Portfolio Architecture Workshop]

TIP: Learn how to develop your own blueprint project and add to this examples reposiotry with https://redhatdemocentral.gitlab.io/portfolio-architecture-template[Beginners guide to deveoping an architecture blueprint]

== Portfolio Architecture Project Index

[cols="1,1,1"]
|===
|General architectures | | Architecture groups

|link:cloud-adoption.adoc[Cloud adoption]
|link:nzd-sap.adoc[Near Zero Downtime Maintenance for SAP]
|link:edge.adoc[Edge]

|link:cloud-factory.adoc[Cloud factory]
|link:omnichannel.adoc[Omnichannel customer experience]
|link:financial-services.adoc[Financial]

|link:cnd.adoc[Cloud native development]
|link:remote-management.adoc[Remote server management]
|link:healthcare.adoc[Healthcare]

|link:data-synthesis.adoc[Modernising testing with data synthesis]
|link:scada-interface.adoc[SCADA interface modernisation]
|link:manufacturing.adoc[Manufacturing]

|link:spi-multi-cloud-gitops.adoc[Hybrid multicloud management with GitOps]
|link:self-healing.adoc[Self-Healing Infrastructure]
|link:retail.adoc[Retail]

|link:integrated-saas.adoc[Integrating with SaaS applications]
|link:sap-smart-management.adoc[Smart management for SAP]
|link:telco.adoc[Telco]

|
|
|link:utility.adoc[Utility]
|===

